# 
# Synthesis run script generated by Vivado
# 

set_param simulator.modelsimInstallPath D:/modeltech_pe_10.4c/win32pe
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/users/bigHW/bigHW.cache/wt [current_project]
set_property parent.project_path D:/users/bigHW/bigHW.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths d:/users/bigHW/bigHW.srcs/sources_1/new [current_project]
add_files D:/users/bigHW/bigHW.srcs/sources_1/new/1.coe
add_files D:/users/bigHW/bigHW.srcs/sources_1/new/repair.coe
add_files D:/users/bigHW/bigHW.srcs/sources_1/new/back.coe
add_files -quiet d:/users/bigHW/bigHW.srcs/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2.dcp
set_property used_in_implementation false [get_files d:/users/bigHW/bigHW.srcs/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2.dcp]
read_verilog -library xil_defaultlib {
  D:/users/bigHW/bigHW.srcs/sources_1/new/Divider.v
  D:/users/bigHW/bigHW.srcs/sources_1/new/vga_control.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/users/bigHW/bigHW.srcs/constrs_1/new/bigHW.xdc
set_property used_in_implementation false [get_files D:/users/bigHW/bigHW.srcs/constrs_1/new/bigHW.xdc]


synth_design -top vga_control -part xc7a100tcsg324-1


write_checkpoint -force -noxdef vga_control.dcp

catch { report_utilization -file vga_control_utilization_synth.rpt -pb vga_control_utilization_synth.pb }
